### PR TITLE
update workflow

### LINKED ISSUE #9: Icon misses from main menu in CI build
The snowflake icon present in screenshot in readme misses in CI build. This is due to not using AutoIt3Wrapper.

Information I have so far:

1. AutoIt3Wrapper does not seem to work when launching it from command line with arguments.
for example `/in FTS.au3` should work but it does not.

2. AutoIt3Wrapper does work when launching it from command line without arguments and then selecting FTS.au3 from the file picker.
`./AutoIt3.exe "C:\Program Files (x86)\AutoIt3\SciTE\AutoIt3Wrapper\AutoIt3Wrapper.au3"`
The above line will launch file picker, after picking FTS.au3 there it compiles with all options set using  `#AutoIt3Wrapper` properly.

I think this is autoit issue but I'm putting it here so I don't forget to look more into it.

### PR DESCRIPTION
**Pull request by micwoj92**
Changes:
- install scite with all tools
- github.repository variable
- use wrapper
- less cd 

Fixes #9 

I wanted to make use of actions/checkout but for some reason it was very unreliable and I have no idea why, all it does is git clone the same way as it's now. Or maybe I am just doing something wrong.

### CODE REVIEW

**Comment by micwoj92** [comment]
So I didn't test it because I was sure that it should work, well

image

The information get set properly but the icons not... And I have 0 idea why.

**Comment by rcmaehl** [comment]
> So I didn't test it because I was sure that it should work, well
> 
> image
> 
> The information get set properly but the icons not... And I have 0 idea why.

Seems like it couldn't find the icon. You may need to Move-Item the Includes folder up a directory.

https://github.com/micwoj92/FreezeToStock/runs/2490720573?check_suite_focus=true#step:4:15

**Comment by micwoj92** [comment]
OK, now it finally works, last 2 runs here are with fix https://github.com/micwoj92/FreezeToStock/actions and I checked for myself

**Comment by micwoj92** [comment]
Now this also resolves #9

**Comment by rcmaehl** [comment]
LGTM

**Pull request merged**
